### ISSUE TITLE
Typo in :gist?

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selbot2#66]
Hi,

Seems like there is a typo in :gist
Looks like instead of saying "or" it says "op", and then "@ polaczek" is shown. 
![image](https://user-images.githubusercontent.com/5992658/31587720-06495812-b1e7-11e7-9d0f-69e9015bfc14.png)

But when I check the code:
https://github.com/SeleniumHQ/selbot2/blob/master/bin/selbot2.rb#L73
Looks fine.

So I am not sure where it comes from, therefore, this issue.

**Comment by lmtierney** [comment]
This is an issue with slackbot (https://github.com/lmtierney/slack-irc) that I need to address.. Basically if it finds text matching a username in slack it changes the text to that user. So people with names of common text get tagged. Not sure why polaczek is getting tagged for "or" but I needed to address it anyway.

**Comment by lmtierney** [comment]
Also of note, what IRC users see is the correct text, it only affects slack.

**Comment by diemol** [comment]
Ah really? OK, I just thought it made sense to report it.
Thanks for the quick response.
